FROM node:latest

COPY . .

COPY /src/aggregationAndRestructure.js /src/index.js

RUN npm i

ENV mongouri=mongodb://mongo:27017/test
ENV database=GuidedSelling
ENV collection=gr_journeyState

ENTRYPOINT ["npm", "run",  "start"]
